# Use the official OpenJDK 21 image as the base image
FROM openjdk:21-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file generated by Gradle
COPY build/libs/stayease-0.0.1-SNAPSHOT.jar /app/stayease.jar

# Copy your application.properties file into the container
#COPY src/main/resources/application.properties /app/application.properties

## Expose port 8080 for the application
#EXPOSE 8080

# Run the Spring Boot application
CMD ["java", "-jar", "stayease.jar"]